import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import videoImg from '/public/img/video.png';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Managed Agency Selection</title>
        <meta name="description" content="Generated by sadkat" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
      </Head>

      <main className={styles.main}>
        <header className={styles.description}>
          <h1 className={styles.title}>Managed agency selection</h1>
          <div>
            <h2>Stengthen your onboarding process</h2>
          </div>
        </header>

        <div className={styles.container}>
          <article className={styles.grid}>
            <div className={styles.left}>
              <Image src={videoImg} alt="/" className={styles.videoImg} />
            </div>

            <div className={styles.right}>
              <a className={styles.card} rel="noopener noreferrer">
                <h2 className={inter.className}>
                  Brief
                </h2>
                <p className={inter.className}>
                  Complete <strong>brief writing or simple guidance</strong> on what to include, we've got you covered.
                </p>
              </a>

              <a className={styles.card} rel="noopener noreferrer">
                <h2 className={inter.className}>
                  Search
                </h2>
                <p className={inter.className}>
                  In-depth agency search covering; <strong>criteria matching</strong>, door knocking and due-dilligence vetting.
                </p>
              </a>

              <a className={styles.card} rel="noopener noreferrer">
                <h2 className={inter.className}>
                  Pitch
                </h2>
                <p className={inter.className}>
                  Comprehensive <strong>pitch management</strong>, including comss, diary management and pitch hosting.
                </p>
              </a>

            </div>
          </article>
        </div>
      </main>
    </>
  )
}
